global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Scrapes Spark executor metrics from the Spark Node over private VPC IP
  - job_name: 'pyspark-lakehouse'
    metrics_path: '/metrics/executors/prometheus'
    static_configs:
      - targets: ['10.0.1.213:4040']
