apiVersion: 1

datasources:
  - name: Athena
    type: grafana-athena-datasource
    access: proxy
    isDefault: false
    jsonData:
      authType: default
      defaultRegion: ap-south-1
      catalog: AwsDataCatalog
      database: default
      workgroup: primary
      outputLocation: s3://enterprise-dataops-dev-athena-results-eba721c2/
